<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-05T20:29:46 IST" name="Default suite" finished-at="2022-11-05T20:30:19 IST" duration-ms="33129">
    <groups>
    </groups>
    <test started-at="2022-11-05T20:29:46 IST" name="Default test" finished-at="2022-11-05T20:30:19 IST" duration-ms="33129">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="Setup()[pri:0, instance:tests.LoginTest@79e2c065]" started-at="2022-11-05T20:29:46 IST" name="Setup" finished-at="2022-11-05T20:29:57 IST" duration-ms="10927" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="ValidateLoginTest()[pri:1, instance:tests.LoginTest@79e2c065]" started-at="2022-11-05T20:29:57 IST" name="ValidateLoginTest" finished-at="2022-11-05T20:30:00 IST" duration-ms="3818" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateLoginTest -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:tests.LoginTest@79e2c065]" started-at="2022-11-05T20:30:00 IST" name="afterTest" finished-at="2022-11-05T20:30:00 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="Setup()[pri:0, instance:tests.LoginTest@79e2c065]" started-at="2022-11-05T20:30:00 IST" name="Setup" finished-at="2022-11-05T20:30:10 IST" duration-ms="9715" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method signature="ValidateDashboardTest()[pri:2, instance:tests.LoginTest@79e2c065]" started-at="2022-11-05T20:30:10 IST" name="ValidateDashboardTest" finished-at="2022-11-05T20:30:19 IST" duration-ms="8448" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [admin] but found [Admin]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [admin] but found [Admin]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at tests.LoginTest.ValidateDashboardTest(LoginTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateDashboardTest -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:tests.LoginTest@79e2c065]" started-at="2022-11-05T20:30:19 IST" name="afterTest" finished-at="2022-11-05T20:30:19 IST" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
